# Default values for sericy-cutopt-glassribbon-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service_type: api
service_name: sericy-cutopt-defectoptimizer-api

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  docker_registry_domain: docker-registry.grenzebach.com
  name: sericy-cutopt-defectoptimizer-api
  tag: "0.291.0-beta.13"

service:
  type: ClusterIP
  port: 8080
  sericy_internal_auth_port: 5000

ingress:
  enabled: true
  proxy_body_size: 15m
  proxy_read_timeout: 60

resources:
   limits:
     memory: 350Mi
   requests:
     cpu: 150m
     memory: 120Mi

global:
  development_phase: dev
  public_domain: subchart.com
  sericy_client: gb
  gb_env: default