{{ $trimmedRelease := .Release.Name | trimSuffix "-dev" }}
{{- if eq $trimmedRelease .Chart.Name }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.development_phase }}-job
  labels: {{- include "labels.standard" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed,hook-succeeded,
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.global.development_phase }}-job
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "alpine:3.18" 
        command: ["/bin/sh", "-c", "apk add --no-cache curl jq bash && cd /home && /home/uploadDefaultConfig.sh"]
        volumeMounts:
        - name: volume
          mountPath: /home/
      volumes:
        - name: volume
          configMap:
            name: {{ .Release.Name }}-{{ .Values.global.development_phase }}-defaultconfig-configmap
            defaultMode: 0777
{{- end }}
