apiVersion: v2
name: sericy-gbs-app-bundle
description: GBS bundle 

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0-beta.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0-beta.5"

dependencies:
  - name: sericy-gbs-cutting-module
    version: ~0.1.0-beta.10
    repository: https://helm-chart-repo.sericy.io/
  - name: sericy-gbs-mfo-module
    version: ~0.1.0-beta.4
    repository: https://helm-chart-repo.sericy.io/
  - name: sericy-om-orders-manager-app
    version: 0.1.0-beta.3
    repository: https://helm-chart-repo.sericy.io/
  - name: sericy-gbs-one-ui
    version: 0.1.0-beta.36
    repository: "file://./charts/sericy-gbs-one-ui"
  - name: sericy-gbs-platedatacache-api
    version: 0.47.0-beta.32
    repository: "file://./charts/sericy-gbs-platedatacache-api"
  - name: sericy-diag-shopfloor-app
    version: 1.2.0-beta.3
    repository: https://helm-chart-repo.sericy.io/
