global:
  development_phase: dev
  public_domain: dev.gbiiot.sericy.io
  sericy_client: gbiiot
  gb_env: gbiiot

tags:
  #CutOpt tags
  wihtFSE: true
  simulation: true
  marking: true

  #MfOpt tags
  fullMfopt: true
  customerLine: false
