global:
  development_phase: dev
  public_domain: dev.gb365.sericy.io
  sericy_client: dev
  gb_env: dev

tags:
  #CutOpt tags
  wihtFSE: true
  simulation: true
  marking: true

  #MfOpt tags
  fullMfopt: true
  customerLine: false

  
